inherit_gem:
  dox-style:
    - .rubocop.yml

AllCops:
  Exclude:
    - "./vendor/**/*"
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - "./**/*_spec*.rb"
    - "./*.gemspec"
    - "./spec/*_helper*.rb"
    - "./tasks/ci.rake"
    - "./lib/tasks/**/*.rake"
    - "Gemfile"

Metrics/ModuleLength:
  Exclude:
    - "./**/*_spec*.rb"

Metrics/MethodLength:
  Exclude:
    - "./**/*_spec*.rb"

Metrics/AbcSize:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 7
Metrics/PerceivedComplexity:
  Max: 8
Metrics/MethodLength:
  Max: 20

Lint/AmbiguousBlockAssociation:
  Exclude:
    - ./**/*_spec.rb
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/FilePath:
  Enabled: false
Rails/ApplicationRecord:
  Enabled: false
